version: "3"

services:
  htn_explorer:
    container_name: htn_explorer
    image: supertypo/htn-explorer:latest
    restart: unless-stopped
    environment:
      API_URI: "http://localhost:8000"
      API_WS_URI: "ws://localhost:8000"
    ports:
      - "8080:8080/tcp"

  htn_rest_server:
    container_name: htn_rest_server
    image: supertypo/htn-rest-server:latest
    restart: unless-stopped
    environment:
      HTND_HOST_1: htnd:16110
      SQL_URI: postgresql+asyncpg://postgres:postgres@postgresql:5432/postgres
    ports:
      - "8000:8000/tcp"
    links:
      - htnd
      - postgresql

  htn_db_filler:
    container_name: htn_db_filler
    image: supertypo/htn-db-filler:latest
    restart: unless-stopped
    environment:
      DEBUG: "true"
      HTND_HOST_1: htnd:16110
      SQL_URI: postgresql://postgres:postgres@postgresql:5432/postgres
    links:
      - htnd
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgresql:/var/lib/postgresql/data/

  htnd:
    container_name: htnd
    image: supertypo/htnd:latest
    restart: unless-stopped
    ports:
      - "16110:16110/tcp"
      - "16111:16111/tcp"
    volumes:
      - htnd:/app/data/
    command: htnd --utxoindex --connect=kdxweb.htncalc.net

volumes:
  postgresql:
  htnd:
